version: "3"

services:
  api:
    build: .
    command: make run-server
    ports:
      - "5000:5000"

  redis:
    image: redis:4.0.9
    ports:
      - "6379:6379"
    volumes:
      - "/tmp/data/redis:/data"

  celery:
    build: .
    command: make run-celery
    depends_on:
      - redis
